<?php

/**
 * @file
 * Sentinel Portal module hooks and utilities.
 */

use Drupal\sentinel_portal_module\SentinelPortalModule;

/**
 * Implements hook_theme().
 */
function sentinel_portal_module_theme($existing, $type, $theme, $path) {
  return SentinelPortalModule::theme($existing, $type, $theme, $path);
}

/**
 * Implements hook_preprocess_block().
 */
function sentinel_portal_module_preprocess_block(&$variables) {
  SentinelPortalModule::preprocessBlock($variables);
}