<?php
/**
 *
 * @file
 * Sentinel Validation Injector.
 *
 * Do not edit this file! It is generated by the system.
 */

if ($appearance_result == 1) {
  $visual_appearance_pass = "1";
  $visual_appearance_feedback = t("", array(), array("langcode" => $lang));
  $recommendations[] = t("", array(), array("langcode" => $lang));
}

elseif ($appearance_result == 2) {
  $visual_appearance_pass = "1";
  $visual_appearance_feedback = t("", array(), array("langcode" => $lang));
  $recommendations[] = t("", array(), array("langcode" => $lang));
 
  
 
}

elseif ($appearance_result == 3 && $system_6_months  === 'MORE6') {
  $visual_appearance_pass = "2";
  $visual_appearance_feedback = t("Water is very turbid", array(), array("langcode" => $lang));
  $recommendations[] = t("System clean and flush required. Clean with Sentinel X400 or Sentinel X800, follow instructions on bottle. Flushing can be manual or power assisted. For optimum results the flushing should be undertaken using a power flushing aid such as Sentinel JetFlush. Ensure all cleaner is thoroughly flushed from the system. Refill and treat with Sentinel X100.", array(), array("langcode" => $lang));
 
  
 
}

elseif ($appearance_result == 3 && $system_6_months  === 'LESS6') {
  $visual_appearance_pass = "2";
  $visual_appearance_feedback = t("Water is very turbid", array(), array("langcode" => $lang));
  $recommendations[] = t("System is less than 6 months old. System clean and flush is required. Clean with Sentinel X300 cleaner. Follow instructions on bottle. Cleaning and flushing can be manual or power assisted. For optimum results the flushing should be undertaken using a power flushing aid such as Sentinel JetFlush. Ensure all cleaner is thoroughly flushed from the system. Refill and treat with Sentinel X100.", array(), array("langcode" => $lang));
 
  
 
}

elseif ($appearance_result == 3 && $system_6_months  === '') {
  $visual_appearance_pass = "2";
  $visual_appearance_feedback = t("Water is very turbid", array(), array("langcode" => $lang));
  $recommendations[] = t("System clean and flush required. Clean using an appropriate Sentinel cleaner, follow instructions on bottle. Flushing can be manual or power assisted. For optimum results the flushing should be undertaken using a power flushing aid such as Sentinel JetFlush. Ensure all cleaner is thoroughly flushed from the system. Refill and treat with Sentinel X100.", array(), array("langcode" => $lang));
 
  
 
}

if ($ph < 6.0 && $system_6_months  === 'MORE6') {
  $ph_level_pass = "2";
  $ph_level_feedback = t("pH too low (acidic), increasing risk of damage to metal components.", array(), array("langcode" => $lang));
  $recommendations[] = t("System clean and flush required. Clean with Sentinel X400 or Sentinel X800, follow instructions on bottle. Flushing can be manual or power assisted. For optimum results the flushing should be undertaken using a power flushing aid such as Sentinel JetFlush. Ensure all cleaner is thoroughly flushed from the system. Refill and treat with Sentinel X100.", array(), array("langcode" => $lang));
 
}

elseif ($ph < 6.0 && $system_6_months  === 'LESS6') {
  $ph_level_pass = "2";
  $ph_level_feedback = t("pH too low (acidic), increasing risk of damage to metal components.", array(), array("langcode" => $lang));
  $recommendations[] = t("System is less than 6 months old. System clean and flush is required. Clean with Sentinel X300 cleaner. Follow instructions on bottle. Cleaning and flushing can be manual or power assisted. For optimum results the flushing should be undertaken using a power flushing aid such as Sentinel JetFlush. Ensure all cleaner is thoroughly flushed from the system. Refill and treat with Sentinel X100.", array(), array("langcode" => $lang));
 
  
}

elseif ($ph < 6.0 && $system_6_months  === '') {
  $ph_level_pass = "2";
  $ph_level_feedback = t("pH too low (acidic), increasing risk of damage to metal components.", array(), array("langcode" => $lang));
  $recommendations[] = t("System clean and flush required. Clean using an appropriate Sentinel cleaner, follow instructions on bottle. Flushing can be manual or power assisted. For optimum results the flushing should be undertaken using a power flushing aid such as Sentinel JetFlush. Ensure all cleaner is thoroughly flushed from the system. Refill and treat with Sentinel X100.", array(), array("langcode" => $lang));
 
 
}

elseif ($ph == 6.0 && $molybdenum_result < 500 && $system_6_months  === 'MORE6') {
  $ph_level_pass = "2";
  $ph_level_feedback = t("pH too low (acidic), increasing risk of damage to metal components.", array(), array("langcode" => $lang));
  $recommendations[] = t("System clean and flush required. Clean with Sentinel X400 or Sentinel X800, follow instructions on bottle. Flushing can be manual or power assisted. For optimum results the flushing should be undertaken using a power flushing aid such as Sentinel JetFlush. Ensure all cleaner is thoroughly flushed from the system. Refill and treat with Sentinel X100.", array(), array("langcode" => $lang));
 
}

elseif ($ph == 6.0 && $molybdenum_result < 500 && $system_6_months  === 'LESS6') {
  $ph_level_pass = "2";
  $ph_level_feedback = t("pH too low (acidic), increasing risk of damage to metal components.", array(), array("langcode" => $lang));
  $recommendations[] = t("System is less than 6 months old. System clean and flush is required. Clean with Sentinel X300 cleaner. Follow instructions on bottle. Cleaning and flushing can be manual or power assisted. For optimum results the flushing should be undertaken using a power flushing aid such as Sentinel JetFlush. Ensure all cleaner is thoroughly flushed from the system. Refill and treat with Sentinel X100.", array(), array("langcode" => $lang));
 
  
}

elseif ($ph == 6.0 && $molybdenum_result < 500 && $system_6_months  === '') {
  $ph_level_pass = "2";
  $ph_level_feedback = t("pH too low (acidic), increasing risk of damage to metal components.", array(), array("langcode" => $lang));
  $recommendations[] = t("System clean and flush required. Clean using an appropriate Sentinel cleaner, follow instructions on bottle. Flushing can be manual or power assisted. For optimum results the flushing should be undertaken using a power flushing aid such as Sentinel JetFlush. Ensure all cleaner is thoroughly flushed from the system. Refill and treat with Sentinel X100.", array(), array("langcode" => $lang));
 
 
}

elseif ($ph > 6.0 && $ph < 6.5 && $molybdenum_result < 500 && $system_6_months  === 'MORE6') {
  $ph_level_pass = "2";
  $ph_level_feedback = t("pH too low (acidic), increasing risk of damage to metal components.", array(), array("langcode" => $lang));
  $recommendations[] = t("System clean and flush required. Clean with Sentinel X400 or Sentinel X800, follow instructions on bottle. Flushing can be manual or power assisted. For optimum results the flushing should be undertaken using a power flushing aid such as Sentinel JetFlush. Ensure all cleaner is thoroughly flushed from the system. Refill and treat with Sentinel X100.", array(), array("langcode" => $lang));
 
}

elseif ($ph > 6.0 && $ph < 6.5 && $molybdenum_result < 500 && $system_6_months  === 'LESS6') {
  $ph_level_pass = "2";
  $ph_level_feedback = t("pH too low (acidic), increasing risk of damage to metal components.", array(), array("langcode" => $lang));
  $recommendations[] = t("System is less than 6 months old. System clean and flush is required. Clean with Sentinel X300 cleaner. Follow instructions on bottle. Cleaning and flushing can be manual or power assisted. For optimum results the flushing should be undertaken using a power flushing aid such as Sentinel JetFlush. Ensure all cleaner is thoroughly flushed from the system. Refill and treat with Sentinel X100.", array(), array("langcode" => $lang));
 
  
}

elseif ($ph > 6.0 && $ph < 6.5 && $molybdenum_result < 500 && $system_6_months  === '') {
  $ph_level_pass = "2";
  $ph_level_feedback = t("pH too low (acidic), increasing risk of damage to metal components.", array(), array("langcode" => $lang));
  $recommendations[] = t("System clean and flush required. Clean using an appropriate Sentinel cleaner, follow instructions on bottle. Flushing can be manual or power assisted. For optimum results the flushing should be undertaken using a power flushing aid such as Sentinel JetFlush. Ensure all cleaner is thoroughly flushed from the system. Refill and treat with Sentinel X100.", array(), array("langcode" => $lang));
 
 
}

elseif ($ph > 6.0 && $ph < 6.5 && $molybdenum_result == 500 && $system_6_months  === 'MORE6') {
  $ph_level_pass = "2";
  $ph_level_feedback = t("pH too low (acidic), increasing risk of damage to metal components.", array(), array("langcode" => $lang));
  $recommendations[] = t("System clean and flush required. Clean with Sentinel X400 or Sentinel X800, follow instructions on bottle. Flushing can be manual or power assisted. For optimum results the flushing should be undertaken using a power flushing aid such as Sentinel JetFlush. Ensure all cleaner is thoroughly flushed from the system. Refill and treat with Sentinel X100.", array(), array("langcode" => $lang));
 
}

elseif ($ph > 6.0 && $ph < 6.5 && $molybdenum_result == 500 && $system_6_months  === 'LESS6') {
  $ph_level_pass = "2";
  $ph_level_feedback = t("pH too low (acidic), increasing risk of damage to metal components.", array(), array("langcode" => $lang));
  $recommendations[] = t("System is less than 6 months old. System clean and flush is required. Clean with Sentinel X300 cleaner. Follow instructions on bottle. Cleaning and flushing can be manual or power assisted. For optimum results the flushing should be undertaken using a power flushing aid such as Sentinel JetFlush. Ensure all cleaner is thoroughly flushed from the system. Refill and treat with Sentinel X100.", array(), array("langcode" => $lang));
 
  
}

elseif ($ph > 6.0 && $ph < 6.5 && $molybdenum_result == 500 && $system_6_months  === '') {
  $ph_level_pass = "2";
  $ph_level_feedback = t("pH too low (acidic), increasing risk of damage to metal components.", array(), array("langcode" => $lang));
  $recommendations[] = t("System clean and flush required. Clean using an appropriate Sentinel cleaner, follow instructions on bottle. Flushing can be manual or power assisted. For optimum results the flushing should be undertaken using a power flushing aid such as Sentinel JetFlush. Ensure all cleaner is thoroughly flushed from the system. Refill and treat with Sentinel X100.", array(), array("langcode" => $lang));
 
 
}

elseif ($ph == 6.0 && $molybdenum_result > 500) {
  $ph_level_pass = "2";
  $ph_level_feedback = t("pH low and inhibitor level very high, possibly insufficient circulation before sampling.", array(), array("langcode" => $lang));
  $recommendations[] = t("Inhibitor level is very high and pH low, likely due to poor system mixing. For a true reading, allow inhibitor to fully circulate (download guidance on SystemCheck page at www.sentinelprotects.com) and re-test.", array(), array("langcode" => $lang));
 
 
}

elseif ($ph > 6.0 && $ph < 6.5 && $molybdenum_result > 500) {
  $ph_level_pass = "2";
  $ph_level_feedback = t("pH low and inhibitor level very high, possibly insufficient circulation before sampling.", array(), array("langcode" => $lang));
  $recommendations[] = t("Inhibitor level is very high and pH low, likely due to poor system mixing. For a true reading, allow inhibitor to fully circulate (download guidance on SystemCheck page at www.sentinelprotects.com) and re-test.", array(), array("langcode" => $lang));
 
 
}

elseif ($ph == 6.5) {
  $ph_level_pass = "1";
  $ph_level_feedback = t("", array(), array("langcode" => $lang));
  $recommendations[] = t("", array(), array("langcode" => $lang));
 
 
 
}

elseif ($boiler_type !== "Worcester Bosch" && $ph > 6.5 && $ph < 8.5) {
  $ph_level_pass = "1";
  $ph_level_feedback = t("", array(), array("langcode" => $lang));
  $recommendations[] = t("", array(), array("langcode" => $lang));
 
 
 
}

elseif ($boiler_type !== "Worcester Bosch" && $ph == 8.5) {
  $ph_level_pass = "1";
  $ph_level_feedback = t("", array(), array("langcode" => $lang));
  $recommendations[] = t("", array(), array("langcode" => $lang));
 
 
 
}

elseif ($boiler_type !== "Worcester Bosch" && $system_6_months  === 'MORE6' && $ph > 8.5) {
  $ph_level_pass = "2";
  $ph_level_feedback = t("pH high (alkaline) and will be corrosive to aluminium in systems", array(), array("langcode" => $lang));
  $recommendations[] = t("System clean and flush required. Clean with Sentinel X400 or Sentinel X800, follow instructions on bottle. Flushing can be manual or power assisted. For optimum results the flushing should be undertaken using a power flushing aid such as Sentinel JetFlush. Ensure all cleaner is thoroughly flushed from the system. Refill and treat with Sentinel X100.", array(), array("langcode" => $lang));
 
 
}

elseif ($boiler_type !== "Worcester Bosch" && $system_6_months  === 'LESS6' && $ph > 8.5) {
  $ph_level_pass = "2";
  $ph_level_feedback = t("pH high (alkaline) and will be corrosive to aluminium in systems", array(), array("langcode" => $lang));
  $recommendations[] = t("System is less than 6 months old. System clean and flush is required. Clean with Sentinel X300 cleaner. Follow instructions on bottle. Cleaning and flushing can be manual or power assisted. For optimum results the flushing should be undertaken using a power flushing aid such as Sentinel JetFlush. Ensure all cleaner is thoroughly flushed from the system. Refill and treat with Sentinel X100.", array(), array("langcode" => $lang));
 
 
}

elseif ($boiler_type !== "Worcester Bosch" && $system_6_months  === '' && $ph > 8.5) {
  $ph_level_pass = "2";
  $ph_level_feedback = t("pH high (alkaline) and will be corrosive to aluminium in systems", array(), array("langcode" => $lang));
  $recommendations[] = t("System clean and flush required. Clean using an appropriate Sentinel cleaner, follow instructions on bottle. Flushing can be manual or power assisted. For optimum results the flushing should be undertaken using a power flushing aid such as Sentinel JetFlush. Ensure all cleaner is thoroughly flushed from the system. Refill and treat with Sentinel X100.", array(), array("langcode" => $lang));
 
  
}

elseif ($boiler_type == "Worcester Bosch" && $ph > 6.5 && $ph < 8.0) {
  $ph_level_pass = "1";
  $ph_level_feedback = t("", array(), array("langcode" => $lang));
  $recommendations[] = t("", array(), array("langcode" => $lang));
 
 
 
}

elseif ($boiler_type == "Worcester Bosch" && $ph == 8.0) {
  $ph_level_pass = "1";
  $ph_level_feedback = t("", array(), array("langcode" => $lang));
  $recommendations[] = t("", array(), array("langcode" => $lang));
 
 
 
}

elseif ($boiler_type == "Worcester Bosch" && $ph > 8.0 && $system_6_months  === 'MORE6') {
  $ph_level_pass = "2";
  $ph_level_feedback = t("pH high (alkaline) and will be corrosive to aluminium in systems", array(), array("langcode" => $lang));
  $recommendations[] = t("System clean and flush required. Clean with Sentinel X400 or Sentinel X800, follow instructions on bottle. Flushing can be manual or power assisted. For optimum results the flushing should be undertaken using a power flushing aid such as Sentinel JetFlush. Ensure all cleaner is thoroughly flushed from the system. Refill and treat with Sentinel X100.", array(), array("langcode" => $lang));
 
 
}

elseif ($boiler_type == "Worcester Bosch" && $ph > 8.0 && $system_6_months  === 'LESS6') {
  $ph_level_pass = "2";
  $ph_level_feedback = t("pH high (alkaline) and will be corrosive to aluminium in systems", array(), array("langcode" => $lang));
  $recommendations[] = t("System is less than 6 months old. System clean and flush is required. Clean with Sentinel X300 cleaner. Follow instructions on bottle. Cleaning and flushing can be manual or power assisted. For optimum results the flushing should be undertaken using a power flushing aid such as Sentinel JetFlush. Ensure all cleaner is thoroughly flushed from the system. Refill and treat with Sentinel X100.", array(), array("langcode" => $lang));
 
 
}

elseif ($boiler_type == "Worcester Bosch" && $ph > 8.0 && $system_6_months  === '') {
  $ph_level_pass = "2";
  $ph_level_feedback = t("pH high (alkaline) and will be corrosive to aluminium in systems", array(), array("langcode" => $lang));
  $recommendations[] = t("System clean and flush required. Clean using an appropriate Sentinel cleaner, follow instructions on bottle. Flushing can be manual or power assisted. For optimum results the flushing should be undertaken using a power flushing aid such as Sentinel JetFlush. Ensure all cleaner is thoroughly flushed from the system. Refill and treat with Sentinel X100.", array(), array("langcode" => $lang));
 
  
}

if ($sys_cond_result > ((($molybdenum_result / 75) * 425) + 15000 + $mains_cond_result) && $system_6_months  === 'MORE6') {
  $conductivity_pass = "2";
  $conductivity_feedback = t("Excess conductivity detected, indicating inadequate flushing has taken place.", array(), array("langcode" => $lang));
  $recommendations[] = t("System clean and flush required. Clean with Sentinel X400 or Sentinel X800, follow instructions on bottle. Flushing can be manual or power assisted. For optimum results the flushing should be undertaken using a power flushing aid such as Sentinel JetFlush. Ensure all cleaner is thoroughly flushed from the system. Refill and treat with Sentinel X100.", array(), array("langcode" => $lang));
 
 
}

elseif ($sys_cond_result > ((($molybdenum_result / 75) * 425) + 15000 + $mains_cond_result) && $system_6_months  === 'LESS6') {
  $conductivity_pass = "2";
  $conductivity_feedback = t("Excess conductivity detected, indicating inadequate flushing has taken place.", array(), array("langcode" => $lang));
  $recommendations[] = t("System is less than 6 months old. System clean and flush is required. Clean with Sentinel X300 cleaner. Follow instructions on bottle. Cleaning and flushing can be manual or power assisted. For optimum results the flushing should be undertaken using a power flushing aid such as Sentinel JetFlush. Ensure all cleaner is thoroughly flushed from the system. Refill and treat with Sentinel X100.", array(), array("langcode" => $lang));
 
 
}

elseif ($sys_cond_result > ((($molybdenum_result / 75) * 425) + 15000 + $mains_cond_result) && $system_6_months  === '') {
  $conductivity_pass = "2";
  $conductivity_feedback = t("Excess conductivity detected, indicating inadequate flushing has taken place.", array(), array("langcode" => $lang));
  $recommendations[] = t("System clean and flush required. Clean using an appropriate Sentinel cleaner, follow instructions on bottle. Flushing can be manual or power assisted. For optimum results the flushing should be undertaken using a power flushing aid such as Sentinel JetFlush. Ensure all cleaner is thoroughly flushed from the system. Refill and treat with Sentinel X100.", array(), array("langcode" => $lang));
 
 
}

elseif ($sys_cond_result == ((($molybdenum_result / 75) * 425) + 15000 + $mains_cond_result)) {
  $conductivity_pass = "1";
  $conductivity_feedback = t("", array(), array("langcode" => $lang));
  $recommendations[] = t("", array(), array("langcode" => $lang));
 
 
 
}

elseif ($sys_cond_result < ((($molybdenum_result / 75) * 425) + 15000 + $mains_cond_result)) {
  $conductivity_pass = "1";
  $conductivity_feedback = t("", array(), array("langcode" => $lang));
  $recommendations[] = t("", array(), array("langcode" => $lang));
 
 
 
}

if ($mains_calcium_result < 40) {
  $calcium_pass = "1";
  $calcium_feedback = t("Mains water hardness is low and would not normally cause scale formation.", array(), array("langcode" => $lang));
  $recommendations[] = t("", array(), array("langcode" => $lang));
 
 
}

elseif ($mains_calcium_result == 40) {
  $calcium_pass = "1";
  $calcium_feedback = t("Mains water hardness is low and would not normally cause scale formation.", array(), array("langcode" => $lang));
  $recommendations[] = t("", array(), array("langcode" => $lang));
 
 
}

elseif ($mains_calcium_result > 40 && $molybdenum_result > 75) {
  $calcium_pass = "1";
  $calcium_feedback = t("Inhibitor level sufficient to prevent scale.", array(), array("langcode" => $lang));
  $recommendations[] = t("", array(), array("langcode" => $lang));
 

}

elseif ($mains_calcium_result > 40 && $molybdenum_result == 75) {
  $calcium_pass = "1";
  $calcium_feedback = t("Inhibitor level sufficient to prevent scale.", array(), array("langcode" => $lang));
  $recommendations[] = t("", array(), array("langcode" => $lang));
 

}

elseif ($mains_calcium_result > 40 && $molybdenum_result < 75 && $sys_calcium_result > (0.75 * $mains_calcium_result)) {
  $calcium_pass = "1";
  $calcium_feedback = t("Calcium level indicates that scale formation has taken place in the boiler.", array(), array("langcode" => $lang));
  $recommendations[] = t("", array(), array("langcode" => $lang));
 
  
}

elseif ($mains_calcium_result > 40 && $molybdenum_result < 75 && $sys_calcium_result == (0.75 * $mains_calcium_result)) {
  $calcium_pass = "1";
  $calcium_feedback = t("Calcium level indicates that scale formation has taken place in the boiler.", array(), array("langcode" => $lang));
  $recommendations[] = t("", array(), array("langcode" => $lang));
 
  
}

elseif ($mains_calcium_result > 40 && $molybdenum_result < 75 && $sys_calcium_result < (0.75 * $mains_calcium_result) && $system_6_months  === 'MORE6') {
  $calcium_pass = "2";
  $calcium_feedback = t("Calcium level indicates that scale formation has taken place in the boiler.", array(), array("langcode" => $lang));
  $recommendations[] = t("System clean and flush required. Clean with Sentinel X400 or Sentinel X800, follow instructions on bottle. Flushing can be manual or power assisted. For optimum results the flushing should be undertaken using a power flushing aid such as Sentinel JetFlush. Ensure all cleaner is thoroughly flushed from the system. Refill and treat with Sentinel X100.", array(), array("langcode" => $lang));
 

}

elseif ($mains_calcium_result > 40 && $molybdenum_result < 75 && $sys_calcium_result < (0.75 * $mains_calcium_result) && $system_6_months  === 'LESS6') {
  $calcium_pass = "2";
  $calcium_feedback = t("Calcium level indicates that scale formation has taken place in the boiler.", array(), array("langcode" => $lang));
  $recommendations[] = t("System is less than 6 months old. System clean and flush is required. Clean with Sentinel X300 cleaner. Follow instructions on bottle. Cleaning and flushing can be manual or power assisted. For optimum results the flushing should be undertaken using a power flushing aid such as Sentinel JetFlush. Ensure all cleaner is thoroughly flushed from the system. Refill and treat with Sentinel X100.", array(), array("langcode" => $lang));
 
 
}

elseif ($mains_calcium_result > 40 && $molybdenum_result < 75 && $sys_calcium_result < (0.75 * $mains_calcium_result) && $system_6_months  === '') {
  $calcium_pass = "2";
  $calcium_feedback = t("Calcium level indicates that scale formation has taken place in the boiler.", array(), array("langcode" => $lang));
  $recommendations[] = t("System clean and flush required. Clean using an appropriate Sentinel cleaner, follow instructions on bottle. Flushing can be manual or power assisted. For optimum results the flushing should be undertaken using a power flushing aid such as Sentinel JetFlush. Ensure all cleaner is thoroughly flushed from the system. Refill and treat with Sentinel X100.", array(), array("langcode" => $lang));
 
 
}

if ($sys_cl_result > 40 && $system_6_months  === 'MORE6') {
  $chloride_pass = "2";
  $chloride_feedback = t("Excess chloride detected, possibly surplus flux from plumbing - corrosion risk.", array(), array("langcode" => $lang));
  $recommendations[] = t("System clean and flush required. Clean with Sentinel X400 or Sentinel X800, follow instructions on bottle. Flushing can be manual or power assisted. For optimum results the flushing should be undertaken using a power flushing aid such as Sentinel JetFlush. Ensure all cleaner is thoroughly flushed from the system. Refill and treat with Sentinel X100.", array(), array("langcode" => $lang));
 
  
}

elseif ($sys_cl_result > 40 && $system_6_months  === 'LESS6') {
  $chloride_pass = "2";
  $chloride_feedback = t("Excess chloride detected, possibly surplus flux from plumbing - corrosion risk.", array(), array("langcode" => $lang));
  $recommendations[] = t("System is less than 6 months old. System clean and flush is required. Clean with Sentinel X300 cleaner. Follow instructions on bottle. Cleaning and flushing can be manual or power assisted. For optimum results the flushing should be undertaken using a power flushing aid such as Sentinel JetFlush. Ensure all cleaner is thoroughly flushed from the system. Refill and treat with Sentinel X100.", array(), array("langcode" => $lang));
 
 
}

elseif ($sys_cl_result > 40 && $system_6_months  === '') {
  $chloride_pass = "2";
  $chloride_feedback = t("Excess chloride detected, possibly surplus flux from plumbing - corrosion risk.", array(), array("langcode" => $lang));
  $recommendations[] = t("System clean and flush required. Clean using an appropriate Sentinel cleaner, follow instructions on bottle. Flushing can be manual or power assisted. For optimum results the flushing should be undertaken using a power flushing aid such as Sentinel JetFlush. Ensure all cleaner is thoroughly flushed from the system. Refill and treat with Sentinel X100.", array(), array("langcode" => $lang));
 

}

elseif ($sys_cl_result == 40) {
  $chloride_pass = "1";
  $chloride_feedback = t("", array(), array("langcode" => $lang));
  $recommendations[] = t("", array(), array("langcode" => $lang));
 
 
}

elseif ($sys_cl_result < 40) {
  $chloride_pass = "1";
  $chloride_feedback = t("", array(), array("langcode" => $lang));
  $recommendations[] = t("", array(), array("langcode" => $lang));
 
}

if ($dissolved_iron > 125 && $system_6_months  === 'MORE6') {
  $dissolved_iron_pass = "2";
  $dissolved_iron_feedback = t("Iron level high, indicating the presence of corrosion debris - system is dirty.", array(), array("langcode" => $lang));
  $recommendations[] = t("System clean and flush required. Clean with Sentinel X400 or Sentinel X800, follow instructions on bottle. Flushing can be manual or power assisted. For optimum results the flushing should be undertaken using a power flushing aid such as Sentinel JetFlush. Ensure all cleaner is thoroughly flushed from the system. Refill and treat with Sentinel X100.", array(), array("langcode" => $lang));
 
  
}

elseif ($dissolved_iron > 125 && $system_6_months  === 'LESS6') {
  $dissolved_iron_pass = "2";
  $dissolved_iron_feedback = t("Iron level high, indicating the presence of corrosion debris - system is dirty.", array(), array("langcode" => $lang));
  $recommendations[] = t("System is less than 6 months old. System clean and flush is required. Clean with Sentinel X300 cleaner. Follow instructions on bottle. Cleaning and flushing can be manual or power assisted. For optimum results the flushing should be undertaken using a power flushing aid such as Sentinel JetFlush. Ensure all cleaner is thoroughly flushed from the system. Refill and treat with Sentinel X100.", array(), array("langcode" => $lang));
 
  
}

elseif ($dissolved_iron > 125 && $system_6_months  === '') {
  $dissolved_iron_pass = "2";
  $dissolved_iron_feedback = t("Iron level high, indicating the presence of corrosion debris - system is dirty.", array(), array("langcode" => $lang));
  $recommendations[] = t("System clean and flush required. Clean using an appropriate Sentinel cleaner, follow instructions on bottle. Flushing can be manual or power assisted. For optimum results the flushing should be undertaken using a power flushing aid such as Sentinel JetFlush. Ensure all cleaner is thoroughly flushed from the system. Refill and treat with Sentinel X100.", array(), array("langcode" => $lang));
 
 
}

elseif ($dissolved_iron == 3 && $molybdenum_result < 75) {
  $dissolved_iron_pass = "2";
  $dissolved_iron_feedback = t("Iron level too high for level of inhibitor to maintain protection.", array(), array("langcode" => $lang));
  $recommendations[] = t("", array(), array("langcode" => $lang));
 

 
}

elseif ($dissolved_iron == 25 && $molybdenum_result < 75) {
  $dissolved_iron_pass = "2";
  $dissolved_iron_feedback = t("Iron level too high for level of inhibitor to maintain protection.", array(), array("langcode" => $lang));
  $recommendations[] = t("", array(), array("langcode" => $lang));
 

 
}

elseif ($dissolved_iron > 3 && $dissolved_iron < 25 && $molybdenum_result < 75) {
  $dissolved_iron_pass = "2";
  $dissolved_iron_feedback = t("Iron level too high for level of inhibitor to maintain protection.", array(), array("langcode" => $lang));
  $recommendations[] = t("", array(), array("langcode" => $lang));
 

 
}

elseif ($dissolved_iron > 25 && $dissolved_iron < 125 && $molybdenum_result < 75 && $system_6_months  === 'MORE6') {
  $dissolved_iron_pass = "2";
  $dissolved_iron_feedback = t("Iron level high, indicating the presence of corrosion debris - system is dirty.", array(), array("langcode" => $lang));
  $recommendations[] = t("System clean and flush required. Clean with Sentinel X400 or Sentinel X800, follow instructions on bottle. Flushing can be manual or power assisted. For optimum results the flushing should be undertaken using a power flushing aid such as Sentinel JetFlush. Ensure all cleaner is thoroughly flushed from the system. Refill and treat with Sentinel X100.", array(), array("langcode" => $lang));
 
  
}

elseif ($dissolved_iron > 25 && $dissolved_iron < 125 && $molybdenum_result < 75 && $system_6_months  === 'LESS6') {
  $dissolved_iron_pass = "2";
  $dissolved_iron_feedback = t("Iron level high, indicating the presence of corrosion debris - system is dirty.", array(), array("langcode" => $lang));
  $recommendations[] = t("System is less than 6 months old. System clean and flush is required. Clean with Sentinel X300 cleaner. Follow instructions on bottle. Cleaning and flushing can be manual or power assisted. For optimum results the flushing should be undertaken using a power flushing aid such as Sentinel JetFlush. Ensure all cleaner is thoroughly flushed from the system. Refill and treat with Sentinel X100.", array(), array("langcode" => $lang));
 
  
}

elseif ($dissolved_iron > 25 && $dissolved_iron < 125 && $molybdenum_result < 75 && $system_6_months  === '') {
  $dissolved_iron_pass = "2";
  $dissolved_iron_feedback = t("Iron level high, indicating the presence of corrosion debris - system is dirty.", array(), array("langcode" => $lang));
  $recommendations[] = t("System clean and flush required. Clean using an appropriate Sentinel cleaner, follow instructions on bottle. Flushing can be manual or power assisted. For optimum results the flushing should be undertaken using a power flushing aid such as Sentinel JetFlush. Ensure all cleaner is thoroughly flushed from the system. Refill and treat with Sentinel X100.", array(), array("langcode" => $lang));
 
 
}

elseif ($dissolved_iron == 125 && $molybdenum_result < 75 && $system_6_months  === 'MORE6') {
  $dissolved_iron_pass = "2";
  $dissolved_iron_feedback = t("Iron level high, indicating the presence of corrosion debris - system is dirty.", array(), array("langcode" => $lang));
  $recommendations[] = t("System clean and flush required. Clean with Sentinel X400 or Sentinel X800, follow instructions on bottle. Flushing can be manual or power assisted. For optimum results the flushing should be undertaken using a power flushing aid such as Sentinel JetFlush. Ensure all cleaner is thoroughly flushed from the system. Refill and treat with Sentinel X100.", array(), array("langcode" => $lang));
 
  
}

elseif ($dissolved_iron == 125 && $molybdenum_result < 75 && $system_6_months  === 'LESS6') {
  $dissolved_iron_pass = "2";
  $dissolved_iron_feedback = t("Iron level high, indicating the presence of corrosion debris - system is dirty.", array(), array("langcode" => $lang));
  $recommendations[] = t("System is less than 6 months old. System clean and flush is required. Clean with Sentinel X300 cleaner. Follow instructions on bottle. Cleaning and flushing can be manual or power assisted. For optimum results the flushing should be undertaken using a power flushing aid such as Sentinel JetFlush. Ensure all cleaner is thoroughly flushed from the system. Refill and treat with Sentinel X100.", array(), array("langcode" => $lang));
 
  
}

elseif ($dissolved_iron == 125 && $molybdenum_result < 75 && $system_6_months  === '') {
  $dissolved_iron_pass = "2";
  $dissolved_iron_feedback = t("Iron level high, indicating the presence of corrosion debris - system is dirty.", array(), array("langcode" => $lang));
  $recommendations[] = t("System clean and flush required. Clean using an appropriate Sentinel cleaner, follow instructions on bottle. Flushing can be manual or power assisted. For optimum results the flushing should be undertaken using a power flushing aid such as Sentinel JetFlush. Ensure all cleaner is thoroughly flushed from the system. Refill and treat with Sentinel X100.", array(), array("langcode" => $lang));
 
 
}

elseif ($dissolved_iron == 3 && $molybdenum_result == 75) {
  $dissolved_iron_pass = "1";
  $dissolved_iron_feedback = t("", array(), array("langcode" => $lang));
  $recommendations[] = t("", array(), array("langcode" => $lang));
 

 
}

elseif ($dissolved_iron == 125 && $molybdenum_result == 75) {
  $dissolved_iron_pass = "1";
  $dissolved_iron_feedback = t("", array(), array("langcode" => $lang));
  $recommendations[] = t("", array(), array("langcode" => $lang));
 

 
}

elseif ($dissolved_iron > 3 && $dissolved_iron < 125 && $molybdenum_result == 75) {
  $dissolved_iron_pass = "1";
  $dissolved_iron_feedback = t("", array(), array("langcode" => $lang));
  $recommendations[] = t("", array(), array("langcode" => $lang));
 

 
}

elseif ($dissolved_iron == 3 && $molybdenum_result > 75) {
  $dissolved_iron_pass = "1";
  $dissolved_iron_feedback = t("", array(), array("langcode" => $lang));
  $recommendations[] = t("", array(), array("langcode" => $lang));
 

 
}

elseif ($dissolved_iron == 125 && $molybdenum_result > 75) {
  $dissolved_iron_pass = "1";
  $dissolved_iron_feedback = t("", array(), array("langcode" => $lang));
  $recommendations[] = t("", array(), array("langcode" => $lang));
 

 
}

elseif ($dissolved_iron > 3 && $dissolved_iron < 125 && $molybdenum_result > 75) {
  $dissolved_iron_pass = "1";
  $dissolved_iron_feedback = t("", array(), array("langcode" => $lang));
  $recommendations[] = t("", array(), array("langcode" => $lang));
 

 
}

elseif ($dissolved_iron < 3) {
  $dissolved_iron_pass = "1";
  $dissolved_iron_feedback = t("", array(), array("langcode" => $lang));
  $recommendations[] = t("", array(), array("langcode" => $lang));
 

 
}

if ($copper_result > 1 && $system_6_months  === 'MORE6') {
  $dissolved_copper_pass = "2";
  $dissolved_copper_feedback = t("Copper level high, indicating corrosion is present - risk of damage to aluminium.", array(), array("langcode" => $lang));
  $recommendations[] = t("System clean and flush required. Clean with Sentinel X400 or Sentinel X800, follow instructions on bottle. Flushing can be manual or power assisted. For optimum results the flushing should be undertaken using a power flushing aid such as Sentinel JetFlush. Ensure all cleaner is thoroughly flushed from the system. Refill and treat with Sentinel X100.", array(), array("langcode" => $lang));
 
  
}

elseif ($copper_result > 1 && $system_6_months  === 'LESS6') {
  $dissolved_copper_pass = "2";
  $dissolved_copper_feedback = t("Copper level high, indicating corrosion is present - risk of damage to aluminium.", array(), array("langcode" => $lang));
  $recommendations[] = t("System is less than 6 months old. System clean and flush is required. Clean with Sentinel X300 cleaner. Follow instructions on bottle. Cleaning and flushing can be manual or power assisted. For optimum results the flushing should be undertaken using a power flushing aid such as Sentinel JetFlush. Ensure all cleaner is thoroughly flushed from the system. Refill and treat with Sentinel X100.", array(), array("langcode" => $lang));
 
 
}

elseif ($copper_result > 1 && $system_6_months  === '') {
  $dissolved_copper_pass = "2";
  $dissolved_copper_feedback = t("Copper level high, indicating corrosion is present - risk of damage to aluminium.", array(), array("langcode" => $lang));
  $recommendations[] = t("System clean and flush required. Clean using an appropriate Sentinel cleaner, follow instructions on bottle. Flushing can be manual or power assisted. For optimum results the flushing should be undertaken using a power flushing aid such as Sentinel JetFlush. Ensure all cleaner is thoroughly flushed from the system. Refill and treat with Sentinel X100.", array(), array("langcode" => $lang));
 
 
}

elseif ($copper_result > 0.6 && $copper_result < 1 && $molybdenum_result < 75) {
  $dissolved_copper_pass = "2";
  $dissolved_copper_feedback = t("Copper level too high for level of inhibitor to maintain protection.", array(), array("langcode" => $lang));
  $recommendations[] = t("", array(), array("langcode" => $lang));
 
 
}

elseif ($copper_result == 1 && $molybdenum_result < 75) {
  $dissolved_copper_pass = "2";
  $dissolved_copper_feedback = t("Copper level too high for level of inhibitor to maintain protection.", array(), array("langcode" => $lang));
  $recommendations[] = t("", array(), array("langcode" => $lang));
 
 
}

elseif ($copper_result > 0.6 && $copper_result < 1 && $molybdenum_result == 75) {
  $dissolved_copper_pass = "1";
  $dissolved_copper_feedback = t("", array(), array("langcode" => $lang));
  $recommendations[] = t("", array(), array("langcode" => $lang));
 
  
 
}

elseif ($copper_result > 0.6 && $copper_result < 1 && $molybdenum_result > 75) {
  $dissolved_copper_pass = "1";
  $dissolved_copper_feedback = t("", array(), array("langcode" => $lang));
  $recommendations[] = t("", array(), array("langcode" => $lang));
 
  
 
}

elseif ($copper_result == 1 && $molybdenum_result == 75) {
  $dissolved_copper_pass = "1";
  $dissolved_copper_feedback = t("", array(), array("langcode" => $lang));
  $recommendations[] = t("", array(), array("langcode" => $lang));
 
  
 
}

elseif ($copper_result == 1 && $molybdenum_result > 75) {
  $dissolved_copper_pass = "1";
  $dissolved_copper_feedback = t("", array(), array("langcode" => $lang));
  $recommendations[] = t("", array(), array("langcode" => $lang));
 
  
 
}

elseif ($copper_result == 0.6) {
  $dissolved_copper_pass = "1";
  $dissolved_copper_feedback = t("", array(), array("langcode" => $lang));
  $recommendations[] = t("", array(), array("langcode" => $lang));
 
  
 
}

elseif ($copper_result < 0.6) {
  $dissolved_copper_pass = "1";
  $dissolved_copper_feedback = t("", array(), array("langcode" => $lang));
  $recommendations[] = t("", array(), array("langcode" => $lang));
 
  
 
}

if ($dissolved_aluminium > 1 && $system_6_months  === 'MORE6') {
  $dissolved_aluminium_pass = "2";
  $dissolved_aluminium_feedback = t("Aluminium level high, indicating presence of corrosion debris.", array(), array("langcode" => $lang));
  $recommendations[] = t("System clean and flush required. Clean with Sentinel X400 or Sentinel X800, follow instructions on bottle. Flushing can be manual or power assisted. For optimum results the flushing should be undertaken using a power flushing aid such as Sentinel JetFlush. Ensure all cleaner is thoroughly flushed from the system. Refill and treat with Sentinel X100.", array(), array("langcode" => $lang));
 
  
}

elseif ($dissolved_aluminium > 1 && $system_6_months  === 'LESS6') {
  $dissolved_aluminium_pass = "2";
  $dissolved_aluminium_feedback = t("Aluminium level high, indicating presence of corrosion debris.", array(), array("langcode" => $lang));
  $recommendations[] = t("System is less than 6 months old. System clean and flush is required. Clean with Sentinel X300 cleaner. Follow instructions on bottle. Cleaning and flushing can be manual or power assisted. For optimum results the flushing should be undertaken using a power flushing aid such as Sentinel JetFlush. Ensure all cleaner is thoroughly flushed from the system. Refill and treat with Sentinel X100.", array(), array("langcode" => $lang));
}

elseif ($dissolved_aluminium > 1 && $system_6_months  === '') {
  $dissolved_aluminium_pass = "2";
  $dissolved_aluminium_feedback = t("Aluminium level high, indicating presence of corrosion debris.", array(), array("langcode" => $lang));
  $recommendations[] = t("System clean and flush required. Clean using an appropriate Sentinel cleaner, follow instructions on bottle. Flushing can be manual or power assisted. For optimum results the flushing should be undertaken using a power flushing aid such as Sentinel JetFlush. Ensure all cleaner is thoroughly flushed from the system. Refill and treat with Sentinel X100.", array(), array("langcode" => $lang));
}

elseif ($dissolved_aluminium == 1 && $molybdenum_result < 75) {
  $dissolved_aluminium_pass = "2";
  $dissolved_aluminium_feedback = t("Aluminium level too high for level of inhibitor to maintain protection.", array(), array("langcode" => $lang));
  $recommendations[] = t("", array(), array("langcode" => $lang));
}

elseif ($dissolved_aluminium > 0.3 && $dissolved_aluminium < 1 && $molybdenum_result < 75) {
  $dissolved_aluminium_pass = "2";
  $dissolved_aluminium_feedback = t("Aluminium level too high for level of inhibitor to maintain protection.", array(), array("langcode" => $lang));
  $recommendations[] = t("", array(), array("langcode" => $lang));
}

elseif ($dissolved_aluminium == 1 && $molybdenum_result == 75) {
  $dissolved_aluminium_pass = "1";
  $dissolved_aluminium_feedback = t("", array(), array("langcode" => $lang));
  $recommendations[] = t("", array(), array("langcode" => $lang));
}

elseif ($dissolved_aluminium > 0.3 && $dissolved_aluminium < 1 && $molybdenum_result == 75) {
  $dissolved_aluminium_pass = "1";
  $dissolved_aluminium_feedback = t("", array(), array("langcode" => $lang));
  $recommendations[] = t("", array(), array("langcode" => $lang));
}

elseif ($dissolved_aluminium == 1 && $molybdenum_result > 75) {
  $dissolved_aluminium_pass = "1";
  $dissolved_aluminium_feedback = t("", array(), array("langcode" => $lang));
  $recommendations[] = t("", array(), array("langcode" => $lang));
}

elseif ($dissolved_aluminium > 0.3 && $dissolved_aluminium < 1 && $molybdenum_result > 75) {
  $dissolved_aluminium_pass = "1";
  $dissolved_aluminium_feedback = t("", array(), array("langcode" => $lang));
  $recommendations[] = t("", array(), array("langcode" => $lang));
}

elseif ($dissolved_aluminium == 0.3) {
  $dissolved_aluminium_pass = "1";
  $dissolved_aluminium_feedback = t("", array(), array("langcode" => $lang));
  $recommendations[] = t("", array(), array("langcode" => $lang));
}

elseif ($dissolved_aluminium < 0.3) {
  $dissolved_aluminium_pass = "1";
  $dissolved_aluminium_feedback = t("", array(), array("langcode" => $lang));
  $recommendations[] = t("", array(), array("langcode" => $lang));
}

if ($molybdenum_result > 500) {
  $x100_pass = "3";
  $x100_feedback = t("Inhibitor level very high, possibly insufficient circulation before sampling.", array(), array("langcode" => $lang));
  $recommendations[] = t("Inhibitor level is very high, likely due to poor system mixing. For protection against corrosion and limescale the system requires a period of normal operation to evenly distribute the inhibitor. For a true reading, allow the system to fully circulate and re-test.", array(), array("langcode" => $lang));
}

elseif ($molybdenum_result == 500) {
  $x100_pass = "1";
  $x100_feedback = t("", array(), array("langcode" => $lang));
  $recommendations[] = t("", array(), array("langcode" => $lang));
}

elseif ($molybdenum_result > 75 && $molybdenum_result < 500) {
  $x100_pass = "1";
  $x100_feedback = t("", array(), array("langcode" => $lang));
  $recommendations[] = t("", array(), array("langcode" => $lang));
}

elseif ($molybdenum_result == 75) {
  $x100_pass = "1";
  $x100_feedback = t("", array(), array("langcode" => $lang));
  $recommendations[] = t("", array(), array("langcode" => $lang));
}

elseif ($molybdenum_result < 75) {
  $x100_pass = "2";
  $x100_feedback = t("Level of inhibitor is too low.", array(), array("langcode" => $lang));
  $recommendations[] = t("The level of inhibitor is too low – Add Sentinel X100 inhibitor.", array(), array("langcode" => $lang));
}
