sentinel_portal.settings:
  type: config_object
  label: 'Sentinel Portal settings'
  mapping:
    new_pack_email:
      type: string
      label: 'Pack submission email'
    stop_emails:
      type: string
      label: 'Email filter list'
