<?php

/**
 * @file
 * Sentinel Portal Notice module.
 */

/**
 * Implements hook_preprocess_page().
 */
function sentinel_portal_notice_preprocess_page(&$variables) {
  // Add CSS to all portal/notices pages
  $current_path = \Drupal::service('path.current')->getPath();
  if (strpos($current_path, '/portal/notices') === 0) {
    $variables['#attached']['library'][] = 'sentinel_portal_notice/notice-styling';
  }
}



